export const imagepath={
    pizza:require('./image/pizza.png'),
    bigpizza:require('./image/pizzabif.png'),
    location:require('./image/location.png'),
    down:require('./image/dropdown.png'),
    sarch:require('./image/surch.png'),
    banner:require('./image/banner.png'),
    meanu:require('./image/meanu.png'),
    burgar:require('./image/barger.png'),
    snaks:require('./image/snakes.png'),
    blackloc:require('./image/locationBlack.png'),
    star:require('./image/star.png'),
    blackprofile:require('./image/profileLogoblack.png'),
    momos:require('../assest/image/momos.png'),
    chole:require('../assest/image/chole.png'),
    paner:require('../assest/image/paner.png'),
    ghar:require('../assest/image/ghar.png'),
    Genie:require('../assest/image/Genie.png'),
    Instamart:require('../assest/image/Instamart.png'),
    rail:require('../assest/image/rail.png'),
    thali:require('../assest/image/panjabithali.png'),
    pizzathali:require('../assest/image/pizzathali.png'),
    barbiq:require('../assest/image/barbiq.png'),
    bargarbanner:require('../assest/image/bargarbanner.png'),
    redstar:require('../assest/image/redstar.png'),
    love:require('../assest/image/love.png'),
    setting:require('../assest/image/setting.png'),
    redlike:require('./image/redlike.png'),
    blacklike:require('./image/blacklike.png'),
    gift:require('./image/gift.png'),
    errow:require('./image/errow.png'),
    map:require('./image/map.png'),
    dboy:require('./image/dboy.png'),
    Vectorlove:require('./image/Vectorlove.png'),
    shoppingBag:require('./image/shoppingBag.png'),
    shoppingBag2:require('./image/shoppingBag2.png'),
    back:require('./image/back.png'),
    shoppingcartpng:require('./image/shoppingcartpng.png'),
    link:require('./image/link.png'),
    sahil1:require('./image/sahil1.png'),
    meggi:require('./image/meggi.png'),
    lockk:require('./image/lock.png'),
    onlockk:require('./image/unlock.png'),
    google:require('./image/google.png'),
    Facebook:require('./image/Facebook.png'),
}
export const colorpath = {
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
    mostuse:"#FF0059"
  };